### PR TITLE
fix: vatsim fetch data changed to https

### PR DESCRIPTION
**Pull request by blt950**
Recently VATSIM Tech forced HTTPS for all requests, and this is when the StatusSync stopped working correctly. Changing it to HTTPS seems to solve the issue and return correct data.

### CODE REVIEW

**Review by skymeyer — APPROVED** [review]

**Comment by blt950** [comment]
@skymeyer Thanks for the approval, would you be so kind to merge it and make a release as well? That way my things using this dependency will work again 🙏🏻

**Comment by skymeyer** [comment]
@blt950 my apologies, I completely forgot about this one. I'll get a new release out in the next 24 hours.

**Comment by winternet-studio** [comment]
Hope you can get to the release soon :)

**Comment by skymeyer** [comment]
This default should be fixed now in latest version https://github.com/skymeyer/Vatsimphp/releases/tag/2.0.4

Thank you all !

**Pull request merged**
